const CLOSE_DRAWER = 'CLOSE_DRAWER';
const OPEN_DRAWER = 'OPEN_DRAWER';
const FETCH_LEVELS = 'FETCH_LEVELS';
const RESET_GAME = 'RESET_GAME';
const SET_CURRENT_CARDS = 'SET_CURRENT_CARDS';
const SET_LEVELS = 'SET_LEVELS';
const TOGGLE_SPOTIFY_WIDGET = 'TOGGLE_SPOTIFY_WIDGET';
const TOGGLE_CARD_MATCH = 'TOGGLE_CARD_MATCH';
const PERSIST_REHYDRATE = 'PERSIST_REHYDRATE';

export {
  CLOSE_DRAWER,
  OPEN_DRAWER,
  FETCH_LEVELS,
  RESET_GAME,
  SET_CURRENT_CARDS,
  SET_LEVELS,
  TOGGLE_SPOTIFY_WIDGET,
  TOGGLE_CARD_MATCH,
  PERSIST_REHYDRATE,
};
