const ADD_MATCH = 'ADD_MATCH';
const ADD_OPEN_ID = 'ADD_OPEN_ID';
const RESET_MEMORY_GAME = 'RESET_MEMORY_GAME';
const SET_OPEN_IDS = 'SET_OPEN_IDS';
const SET_MATCHED_CARDS = 'SET_MATCHED_CARDS';
const START_GAME = 'START_GAME';

export {
  ADD_MATCH,
  ADD_OPEN_ID,
  RESET_MEMORY_GAME,
  SET_OPEN_IDS,
  SET_MATCHED_CARDS,
  START_GAME,
};
